[build]
builder      = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache"

[nixpacks]
workdir = "backend"

[deploy]
startCommand = "sh -c \'cd backend && php -S 0.0.0.0:$PORT public/index.php\'"
restartPolicyType = "ON_FAILURE"
