[build]
builder      = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev && npm install && npm run build && php artisan config:cache && php artisan route:cache"

[nixpacks]
workdir = "backend"

[deploy]
startCommand = "sh -c \"echo '<?php echo \\\"Hello World\\\";' > public/hello.php && php -S 0.0.0.0:$PORT -t public\""
restartPolicyType = "ON_FAILURE"
